openapi: 3.0.0

info:
  title: RBAC
  description: The API collection for a Role-based access control system
  version: 1.0.0

servers:
  - url: http://localhost:4000/api
    description: Shopease Development Server

tags:
  - name: Authentication
    description: Authentication API
  - name: Users
    description: Users API
  - name: Roles
    description: Roles API

paths:
  /auth/signup:
    post:
      tags:
        - Authentication
      description: Allows users to create an account
      operationId: signup
      requestBody:
        description: A JSON object containing signup info
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        '201':
          description: A JSON object containing a newly created user
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/User'

  /auth/login:
    post:
      tags:
        - Authentication
      description: Allows users to login using their email address and password
      operationId: login
      requestBody:
        description: A JSON object containing login info
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'

  /auth/logout:
    post:
      tags:
        - Authentication
      description: Allows users to log out
      operationId: logout
      responses:
        '200':
          description: Logout success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'

  /auth/password/forgot:
    post:
      tags:
        - Authentication
      description: Sends an email to the user with reset password link
      operationId: forgotPassword
      requestBody:
        description: A JSON object containing an email address
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Password reset email sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'

  /auth/password/reset/{token}:
    put:
      tags:
        - Authentication
      description: Allows users to reset their account password
      operationId: resetPassword
      parameters:
        - in: path
          name: token
          required: true
          description: Reset password token
          schema:
            type: string
      requestBody:
        description: A JSON object containing new and confirmed passwords
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        '200':
          description: Password reset success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'

components:
  schemas:
    Success:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    User:
      type: object
      properties:
        id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        fullname:
          type: string
        email:
          type: string
        phone:
          type: string
        role:
          type: string
        avatar:
          type: object
          properties:
            url:
              type: string
            publicId:
              type: string
        isActive:
          type: boolean
        resetPasswordToken:
          type: string
        resetPasswordExpiry:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
